<a href="https://colab.research.google.com/github/ANEUP002/Trigram-Character-Level-Name-Generator/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import torch.nn.functional as F

In [1]:
words = open('names.txt','r').read().splitlines()

In [2]:
char = sorted(list(set(''.join(words))))

In [7]:
stoi = {s:i+1 for i,s in enumerate(char)}
stoi['.']=0

In [9]:
isto = {i:s for s,i in stoi.items()}

In [18]:
N = torch.zeros([27,27,27],dtype=torch.int32)

In [23]:
N

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [26]:
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    N[ix1, ix2, ix3] += 1


In [27]:
N

tensor([[[  0,   0,   0,  ...,   0,   0,   0],
         [  0, 207, 190,  ...,  27, 173, 152],
         [  0, 169,   0,  ...,   0,   4,   0],
         ...,
         [  0,  57,   0,  ...,   1,  17,  11],
         [  0, 246,   0,  ...,   0,   0,   2],
         [  0, 456,   0,  ...,   0,  91,   1]],

        [[  0,   0,   0,  ...,   0,   0,   0],
         [ 40,   0,   5,  ...,   0,  20,  11],
         [ 36,  28,  20,  ...,   0,  12,   0],
         ...,
         [ 11,   5,   0,  ...,  17,   6,   3],
         [163, 389,  13,  ...,   0,  16,  40],
         [ 38, 123,   0,  ...,   0,  12,  22]],

        [[  0,   0,   0,  ...,   0,   0,   0],
         [ 46,   5,   5,  ...,   4,  31,   4],
         [  1,   8,   0,  ...,   0,   9,   0],
         ...,
         [  0,   0,   0,  ...,   0,   0,   0],
         [ 55,   4,   1,  ...,   0,   0,   0],
         [  0,   0,   0,  ...,   0,   0,   0]],

        ...,

        [[  0,   0,   0,  ...,   0,   0,   0],
         [ 10,   0,   2,  ...,   0,  10,   0]

In [28]:
g = torch.Generator().manual_seed(2147483647)

In [45]:
P = (N + 1).float()
P /= P.sum(2, keepdim=True)

In [48]:
for i in range(10):
  ix1 = 0
  ix2 = 0
  out =[]
  while True:
    p = P[ix1, ix2]
    ix1 = ix2
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(isto[ix])
    if ix == 0:
      break
    ix1, ix2 = ix2, ix
  print(''.join(out))


frandam.
favisotten.
salee.
grin.
noew.
fabethellianten.
chan.
ura.
odridyden.
jhaliypvrgia.


In [54]:
for w in words:
  n = 0
  likelihood = 0.0
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    prob = P[ix1, ix2, ix3]
    logprob = torch.log(prob)
    likelihood += logprob
    n += 1

    print(f'{ch1}{ch2}{ch3}: {prob:.4f} {logprob:.4f} {likelihood:.4f}')

print(f"{likelihood=}")
nll = -likelihood
print(f'{nll/n=}')


Streaming output truncated to the last 5000 lines.
yte: 0.1603 -1.8307 -14.0120
ten: 0.1534 -1.8745 -15.8865
en.: 0.4508 -0.7968 -16.6833
.kl: 0.0104 -4.5690 -4.5690
kli: 0.1024 -2.2788 -6.8478
lin: 0.2016 -1.6015 -8.4493
int: 0.0200 -3.9134 -12.3627
nto: 0.1170 -2.1454 -14.5081
ton: 0.5447 -0.6076 -15.1157
on.: 0.6169 -0.4830 -15.5988
.kn: 0.0077 -4.8675 -4.8675
kni: 0.1321 -2.0244 -6.8919
nig: 0.0057 -5.1659 -12.0578
igh: 0.6396 -0.4470 -12.5048
ght: 0.0853 -2.4619 -14.9667
hte: 0.1224 -2.1001 -17.0668
ten: 0.1534 -1.8745 -18.9413
en.: 0.4508 -0.7968 -19.7381
.kn: 0.0077 -4.8675 -4.8675
kni: 0.1321 -2.0244 -6.8919
nix: 0.0166 -4.1012 -10.9931
ixo: 0.0948 -2.3557 -13.3488
xon: 0.4412 -0.8183 -14.1671
on.: 0.6169 -0.4830 -14.6502
.kn: 0.0077 -4.8675 -4.8675
knu: 0.0377 -3.2771 -8.1447
nut: 0.0163 -4.1190 -12.2637
ute: 0.0275 -3.5927 -15.8565
te.: 0.2369 -1.4402 -17.2967
.ko: 0.0645 -2.7403 -2.7403
koa: 0.0377 -3.2771 -6.0175
oan: 0.2443 -1.4093 -7.4268
an.: 0.2763 -1.2863 -8.7130
.ko: 

In [57]:
xs = []
ys = []
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    xs.append((stoi[ch1],stoi[ch2]))
    ys.append(stoi[ch3])
xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [58]:
xs

tensor([[ 0,  5],
        [ 5, 13],
        [13, 13],
        ...,
        [26, 25],
        [25, 26],
        [26, 24]])

In [59]:
ys

tensor([13, 13,  1,  ..., 26, 24,  0])

In [60]:
xs.shape

torch.Size([196113, 2])

In [61]:
ys.shape

torch.Size([196113])

In [62]:
xs[1]

tensor([ 5, 13])

In [63]:
ys[1]

tensor(13)

In [77]:
W = torch.randn((27*2, 27), requires_grad=True)

In [81]:
for i in range(10):
  x1 = F.one_hot(xs[:,0]).float()
  x2 = F.one_hot(xs[:,1]).float()
  xenc = torch.cat([x1,x2],dim =1 )
  logits = xenc @ W
  probs = F.log_softmax(logits, dim=1)
  loss = -probs[torch.arange(xs.shape[0]), ys].mean()
  W.grad = None
  loss.backward()
  W.data += -0.4 * W.grad
  print(loss.item())

3.871581792831421
3.865211248397827
3.8588738441467285
3.8525686264038086
3.846296548843384
3.840056896209717
3.8338499069213867
3.8276753425598145
3.821533441543579
3.8154239654541016


In [106]:
for i in range(100):
  x1 = F.one_hot(xs[:,0]).float()
  x2 = F.one_hot(xs[:,1]).float()
  xenc = torch.cat([x1,x2],dim =1 )
  logits = xenc @ W
  probs = F.log_softmax(logits, dim=1)
  loss = -probs[torch.arange(xs.shape[0]), ys].mean()
  W.grad = None
  loss.backward()
  W.data += -0.6 * W.grad
  print(loss.item())

2.6111433506011963
2.60373854637146
2.596470832824707
2.589337110519409
2.582336187362671
2.575467109680176
2.568727493286133
2.5621163845062256
2.5556318759918213
2.5492730140686035
2.5430374145507812
2.536924362182617
2.5309317111968994
2.5250585079193115
2.5193018913269043
2.5136616230010986
2.5081350803375244
2.502721071243286
2.49741792678833
2.4922235012054443
2.4871366024017334
2.4821553230285645
2.4772770404815674
2.472501277923584
2.467825412750244
2.4632480144500732
2.4587671756744385
2.454380512237549
2.450087308883667
2.4458847045898438
2.4417712688446045
2.4377450942993164
2.433804750442505
2.429947853088379
2.426173448562622
2.422478675842285
2.418862819671631
2.415323257446289
2.4118590354919434
2.4084677696228027
2.405148506164551
2.4018986225128174
2.3987181186676025
2.395603656768799
2.392554759979248
2.3895692825317383
2.3866465091705322
2.383784532546997
2.3809814453125
2.378236770629883
2.3755486011505127
2.372915506362915
2.3703365325927734
2.3678102493286133
2.36

In [107]:
W

tensor([[-4.0948,  2.3772,  0.0685,  ..., -1.0606,  0.6744,  0.7292],
        [ 1.3662,  0.6192,  0.1026,  ..., -1.1525,  0.1043,  0.2049],
        [ 0.7524,  1.7959, -0.0412,  ...,  0.1263,  1.0519, -0.6374],
        ...,
        [ 1.5308,  1.4041,  0.3718,  ...,  1.6357,  1.1639,  1.0515],
        [ 1.4649,  1.8677, -0.8681,  ..., -0.8637, -2.0280, -0.0728],
        [ 0.5300,  2.6011, -0.3980,  ..., -0.7162,  1.7637,  0.6848]],
       requires_grad=True)

In [108]:
for i in range(10):
  out = []
  ix1 = 0
  ix2 = 0
  while True:
    t1 = F.one_hot(torch.tensor([ix1]),num_classes=27).float()
    t2 = F.one_hot(torch.tensor([ix2]), num_classes=27).float()
    xenc = torch.cat([t1,t2],dim =1)
    logits = xenc @ W
    probs = F.softmax(logits, dim=1)
    ix = torch.multinomial(probs, num_samples=1, replacement=True, generator=g).item()
    out.append(isto[ix])
    if ix == 0:
      break
    ix1 , ix2 = ix2, ix
  print(''.join(out))


abi.
diaylyn.
aan.
ie.
ahas.
frestei.
xisharimaiveron.
abiy.
iaghanye.
igan.
